const league = 
  {
    new_entries: { has_next: false, number: 1, results: [] },
    league: {
      id: 765405,
      leagueban_set: [],
      name: 'Fish & Crumple-Ones',
      short_name: null,
      created: '2018-08-09T04:02:42Z',
      closed: false,
      forum_disabled: false,
      make_code_public: false,
      rank: null,
      size: null,
      league_type: 'x',
      _scoring: 'c',
      reprocess_standings: false,
      admin_entry: 446958,
      start_event: 1,
    },
    standings: {
      has_next: false,
      number: 1,
      results: [
        {
          id: 19080407,
          entry_name: 'babybelend',
          event_total: 65,
          player_name: 'alex balick',
          movement: 'same',
          own_entry: false,
          rank: 1,
          last_rank: 1,
          rank_sort: 1,
          total: 2214,
          entry: 963600,
          league: 765405,
          start_event: 1,
          stop_event: 38,
        },
        {
          id: 19080403,
          entry_name: 'Kim Jong Kün',
          event_total: 54,
          player_name: 'Benjamin Lurie',
          movement: 'same',
          own_entry: false,
          rank: 2,
          last_rank: 2,
          rank_sort: 2,
          total: 2155,
          entry: 446958,
          league: 765405,
          start_event: 1,
          stop_event: 38,
        },
        {
          id: 20602343,
          entry_name: "Goldberg's Dele",
          event_total: 64,
          player_name: 'Ian Goldberg',
          movement: 'up',
          own_entry: false,
          rank: 3,
          last_rank: 4,
          rank_sort: 3,
          total: 2107,
          entry: 3587639,
          league: 765405,
          start_event: 1,
          stop_event: 38,
        },
        {
          id: 19080408,
          entry_name: 'Obama’s Yang',
          event_total: 40,
          player_name: 'Brett Saltzman',
          movement: 'down',
          own_entry: false,
          rank: 4,
          last_rank: 3,
          rank_sort: 4,
          total: 2089,
          entry: 954954,
          league: 765405,
          start_event: 1,
          stop_event: 38,
        },
        {
          id: 19080404,
          entry_name: '@ChicagoSeagulls',
          event_total: 68,
          player_name: 'Benjamin Sinaiko',
          movement: 'same',
          own_entry: false,
          rank: 5,
          last_rank: 5,
          rank_sort: 5,
          total: 2080,
          entry: 1790869,
          league: 765405,
          start_event: 1,
          stop_event: 38,
        },
        {
          id: 22198524,
          entry_name: 'CHANGE NAME',
          event_total: 72,
          player_name: 'Jon Margolis',
          movement: 'same',
          own_entry: false,
          rank: 6,
          last_rank: 6,
          rank_sort: 6,
          total: 2044,
          entry: 3015585,
          league: 765405,
          start_event: 1,
          stop_event: 38,
        },
        {
          id: 22356874,
          entry_name: 'Leeds vs Villa',
          event_total: 56,
          player_name: 'paul damato',
          movement: 'same',
          own_entry: false,
          rank: 7,
          last_rank: 7,
          rank_sort: 7,
          total: 2022,
          entry: 3863048,
          league: 765405,
          start_event: 1,
          stop_event: 38,
        },
        {
          id: 19080406,
          entry_name: 'CHANGE NAME',
          event_total: 27,
          player_name: 'andy Rosenband',
          movement: 'same',
          own_entry: false,
          rank: 8,
          last_rank: 8,
          rank_sort: 8,
          total: 1957,
          entry: 1643394,
          league: 765405,
          start_event: 1,
          stop_event: 38,
        },
        {
          id: 19080405,
          entry_name: "WINP '17",
          event_total: 43,
          player_name: 'Jonathan Mirkin',
          movement: 'same',
          own_entry: false,
          rank: 9,
          last_rank: 9,
          rank_sort: 9,
          total: 1924,
          entry: 3357969,
          league: 765405,
          start_event: 1,
          stop_event: 38,
        },
      ],
    },
    update_status: 0,
  },


const leagueGlobal = [
  {
    league: 'Overall',
    standings: [
      {
        id: 512077,
        entry_name: '#TheyAreUs',
        event_total: 71,
        player_name: 'Adam Levy',
        movement: 'same',
        own_entry: false,
        rank: 1,
        last_rank: 1,
        rank_sort: 1,
        total: 2659,
        entry: 107827,
        league: 313,
        start_event: 1,
        stop_event: 38,
      },
      {
        id: 2997508,
        entry_name: "Sutton's Wonder's",
        event_total: 83,
        player_name: 'james sutton',
        movement: 'up',
        own_entry: false,
        rank: 2,
        last_rank: 5,
        rank_sort: 2,
        total: 2602,
        entry: 616809,
        league: 313,
        start_event: 1,
        stop_event: 38,
      },
      {
        id: 842222,
        entry_name: 'Salah my name',
        event_total: 78,
        player_name: 'Andrew Green',
        movement: 'up',
        own_entry: false,
        rank: 3,
        last_rank: 8,
        rank_sort: 3,
        total: 2589,
        entry: 176339,
        league: 313,
        start_event: 1,
        stop_event: 38,
      },
      {
        id: 2957293,
        entry_name: 'Badelj 1862',
        event_total: 69,
        player_name: 'Domagoj Fekonja',
        movement: 'same',
        own_entry: false,
        rank: 4,
        last_rank: 4,
        rank_sort: 4,
        total: 2589,
        entry: 609081,
        league: 313,
        start_event: 1,
        stop_event: 38,
      },
      {
        id: 1585118,
        entry_name: 'Gullit',
        event_total: 63,
        player_name: '🇴🇲 Falah Allawati (Oman) 🇴🇲',
        movement: 'down',
        own_entry: false,
        rank: 5,
        last_rank: 2,
        rank_sort: 5,
        total: 2587,
        entry: 328368,
        league: 313,
        start_event: 1,
        stop_event: 38,
      },
    ],
  },
  {
    league: 'USA',
    standings: [
      {
        id: 663437,
        entry_name: 'Square Wheels FC',
        event_total: 54,
        player_name: 'Jay Lovejoy',
        movement: 'same',
        own_entry: false,
        rank: 1,
        last_rank: 1,
        rank_sort: 1,
        total: 2570,
        entry: 138561,
        league: 249,
        start_event: 1,
        stop_event: 38,
      },
      {
        id: 2282259,
        entry_name: 'BloccFPL',
        event_total: 45,
        player_name: 'Chase Blocker',
        movement: 'same',
        own_entry: false,
        rank: 2,
        last_rank: 2,
        rank_sort: 2,
        total: 2537,
        entry: 473996,
        league: 249,
        start_event: 1,
        stop_event: 38,
      },
      {
        id: 40185,
        entry_name: 'Garden of Eden',
        event_total: 59,
        player_name: 'David Golann',
        movement: 'same',
        own_entry: false,
        rank: 3,
        last_rank: 3,
        rank_sort: 3,
        total: 2528,
        entry: 8450,
        league: 249,
        start_event: 1,
        stop_event: 38,
      },
      {
        id: 8286918,
        entry_name: 'Sporting Milwaukee',
        event_total: 57,
        player_name: 'C.J. Krawczyk',
        movement: 'same',
        own_entry: false,
        rank: 4,
        last_rank: 4,
        rank_sort: 4,
        total: 2515,
        entry: 1593197,
        league: 249,
        start_event: 1,
        stop_event: 38,
      },
      {
        id: 290944,
        entry_name: 'Goonsquad',
        event_total: 76,
        player_name: 'Ryan Maleknia',
        movement: 'up',
        own_entry: false,
        rank: 5,
        last_rank: 9,
        rank_sort: 5,
        total: 2509,
        entry: 61736,
        league: 249,
        start_event: 1,
        stop_event: 38,
      },
    ],
  },
]

export { league, leagueGlobal }
