// Status Actions
export const FETCH_STATUS_START = 'FETCH_STATUS_START';
export const FETCH_STATUS_SUCCESS = 'FETCH_STATUS_SUCCESS';
export const FETCH_STATUS_FAIL = 'FETCH_STATUS_FAIL';

// League Actions
export const FETCH_LEAGUE_START = 'FETCH_LEAGUE_START';
export const FETCH_LEAGUE_SUCCESS = 'FETCH_LEAGUE_SUCCESS';
export const FETCH_LEAGUE_FAIL = 'FETCH_LEAGUE_FAIL';
export const FETCH_GLOBAL_START = 'FETCH_GLOBAL_START';
export const FETCH_GLOBAL_SUCCESS = 'FETCH_GLOBAL_SUCCESS';
export const FETCH_GLOBAL_FAIL = 'FETCH_GLOBAL_FAIL';

// Player Actions
export const FETCH_PLAYERS_DATA_START = 'FETCH_PLAYERS_DATA_START';
export const FETCH_PLAYERS_DATA_SUCCESS = 'FETCH_PLAYERS_DATA_SUCCESS';
export const FETCH_PLAYERS_DATA_FAIL = 'FETCH_PLAYERS_DATA_FAIL';
