export const EVENTS_LOADING = 'EVENTS_LOADING';
export const GET_EVENTS = 'GET_EVENTS';
export const GET_EVENT = 'GET_EVENT';
export const LEAGUE_LOADING = 'LEAGUE_LOADING';
export const GET_LEAGUE_STANDINGS = 'GET_LEAGUE_STANDINGS';
